__title__ = 'odoo-bin'
__version__ = '0.0.1'
__author__ = 'Jose Noguera'
__email__ = 'josenoguera1994@gmail.com'
__description__ = 'odoo-bin core of odoo by OpenERP SA, installer of odoo modules with scaffold command among other functions'
__url__ = 'https://github.com/josenoguera-94/odoo-bin'